[package]
name = "rustmeter-beacon"
version = "0.2.0"
edition = "2024"
license = "MIT"
authors = ["Christopher Kock"]
description = "Lightweight tracing library for embedded Rust applications"
repository = "https://github.com/Christopher-06/rustmeter"
keywords = ["embedded", "tracing", "profiling", "no-std", "embassy"]
categories = ["embedded", "development-tools::profiling", "no-std"]
exclude = ["/debug", "/target", ".gitignore"]
readme = "README.md"
documentation = "https://docs.rs/rustmeter-beacon"

[dependencies]
rustmeter-beacon-proc-macros = { path = "rustmeter-beacon-proc-macros", version = "0.2.0" }
rustmeter-beacon-core = { path = "rustmeter-beacon-core", version = "0.2.0" }
rustmeter-beacon-target = { path = "rustmeter-beacon-target", version = "0.2.0" }

defmt = { version = "1", optional = true }
portable-atomic = "1"

[features]
stm32 = ["rustmeter-beacon-target/stm32"]
esp32 = ["rustmeter-beacon-target/esp32"]
esp32c2 = ["rustmeter-beacon-target/esp32c2"]
esp32c3 = ["rustmeter-beacon-target/esp32c3"]
esp32c6 = ["rustmeter-beacon-target/esp32c6"]
esp32h2 = ["rustmeter-beacon-target/esp32h2"]
esp32s2 = ["rustmeter-beacon-target/esp32s2"]
esp32s3 = ["rustmeter-beacon-target/esp32s3"]
rp2040 = ["rustmeter-beacon-target/rp2040"]
defmt = ["dep:defmt", "rustmeter-beacon-target/defmt"]
